/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/flags_1.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Flags_1(props) {
  const { nodes, materials } = useGLTF('/models/flags_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane003.geometry} material={materials.Fox} />
      <mesh geometry={nodes.Plane003_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane013.geometry} material={materials.Detection} />
      <mesh geometry={nodes.Plane013_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane014.geometry} material={materials.Reflection} />
      <mesh geometry={nodes.Plane014_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane015.geometry} material={materials.Twins} />
      <mesh geometry={nodes.Plane015_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Power} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane010.geometry} material={materials.Titans} />
      <mesh geometry={nodes.Plane010_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane011.geometry} material={materials.Giants} />
      <mesh geometry={nodes.Plane011_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane012.geometry} material={materials.Skill} />
      <mesh geometry={nodes.Plane012_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.Enlightenment} />
      <mesh geometry={nodes.Plane002_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane004.geometry} material={materials.Protection} />
      <mesh geometry={nodes.Plane004_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane005.geometry} material={materials.Perfection} />
      <mesh geometry={nodes.Plane005_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane006.geometry} material={materials.Brilliance} />
      <mesh geometry={nodes.Plane006_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Anger} />
      <mesh geometry={nodes.Plane001_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane007.geometry} material={materials.Rage} />
      <mesh geometry={nodes.Plane007_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane008.geometry} material={materials.Vitriol} />
      <mesh geometry={nodes.Plane008_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane009.geometry} material={materials.Fury} />
      <mesh geometry={nodes.Plane009_1.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('/models/flags_1-transformed.glb')
